FROM python:3.11.4-slim-bullseye

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /home/app/web


COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .

# RUN apt-get update # dont update!! 

