# Generated by Django 5.0.6 on 2024-06-04 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_userprofile_name_alter_startup_pitch_deck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('meet_link', models.URLField()),
                ('recording', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('meet_duration', models.IntegerField(default=45)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='users.userprofile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='users.userprofile')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meetingslot')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_link', models.URLField()),
                ('minutes_of_meet', models.TextField(blank=True, null=True)),
                ('requester_feedback_score', models.IntegerField(blank=True, null=True)),
                ('requested_feedback_score', models.IntegerField(blank=True, null=True)),
                ('recording', models.URLField(blank=True, null=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.meetingslot')),
            ],
        ),
    ]
