# Generated by Django 5.0.6 on 2024-06-08 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrequest',
            name='meet_duration',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='start_time',
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='minutes_of_meet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='recording',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='requested_feedback_score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='requester_feedback_score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='globalevent',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]