# Generated by Django 5.0.6 on 2024-06-12 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_remove_meetingrequest_meet_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='slot_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='slot_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingslot',
            name='free',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meetingslot'),
        ),
        migrations.AlterField(
            model_name='meetingslot',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meetingslot',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
