# Generated by Django 5.0.6 on 2024-06-19 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingrequest_slot_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalevent',
            name='event_date',
        ),
        migrations.AddField(
            model_name='globalevent',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='globalevent',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='cel_approved',
            field=models.BooleanField(default=False),
        ),
    ]