# Generated by Django 5.0.6 on 2024-06-21 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_remove_globalevent_event_date_globalevent_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='globalevent',
            name='start_time',
        ),
        migrations.AddField(
            model_name='globalevent',
            name='slot_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='globalevent',
            name='slot_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
