# Generated by Django 5.0.6 on 2024-06-04 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_userprofile_name_alter_startup_pitch_deck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FileAns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.URLField()),
                ('under_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.answer')),
                ('file_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.fileuploadquestion')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('available_to', models.ManyToManyField(to='users.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='fileuploadquestion',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_questions', to='forms.form'),
        ),
        migrations.AddField(
            model_name='answer',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.form'),
        ),
        migrations.CreateModel(
            name='PreferenceAnsMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.answer')),
            ],
            options={
                'verbose_name': 'Preference Question',
                'verbose_name_plural': 'Preference Questions',
            },
        ),
        migrations.CreateModel(
            name='PreferenceAns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('preference_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.preference')),
                ('preference_ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.preferenceansmain')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_questions', to='forms.form')),
            ],
        ),
        migrations.AddField(
            model_name='preferenceansmain',
            name='preference_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.preferencequestion'),
        ),
        migrations.AddField(
            model_name='preference',
            name='under_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='forms.preferencequestion'),
        ),
        migrations.CreateModel(
            name='ScoringQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_questions', to='forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreAns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(default=1)),
                ('under_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.answer')),
                ('scoring_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.scoringquestion')),
            ],
            options={
                'verbose_name': 'Scoring Answer',
                'verbose_name_plural': 'Scoring Answers',
            },
        ),
        migrations.CreateModel(
            name='SubjectiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjective_questions', to='forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectiveAns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('under_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.answer')),
                ('subjective_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.subjectivequestion')),
            ],
            options={
                'verbose_name': 'Subjective Answer',
                'verbose_name_plural': 'Subjective Answers',
            },
        ),
    ]
