# Generated by Django 5.0.6 on 2024-06-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectivequestion',
            name='type',
            field=models.CharField(choices=[('Single Line', 'Single Line'), ('Short', 'Short'), ('Long', 'Long')], default='Long', max_length=11),
        ),
    ]
