# Generated by Django 5.0.6 on 2024-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='roles',
            field=models.CharField(default='Startup', max_length=390),
        ),
    ]