# Generated by Django 5.0.6 on 2024-07-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_announcement_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='roles',
            field=models.CharField(default='Startup', max_length=420),
        ),
    ]
