# Generated by Django 5.0.6 on 2024-05-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach_Mentor_Experts_others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_logo', models.ImageField(upload_to='')),
                ('designation', models.CharField(max_length=100)),
                ('linkedin', models.URLField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('Resume', models.URLField()),
                ('role', models.TextField()),
                ('sector_expertise', models.TextField()),
                ('domain_expertise', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=100)),
                ('picture_logo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('stage', models.TextField()),
                ('industry', models.TextField()),
                ('location_hq', models.TextField()),
                ('pitch_deck', models.FileField(upload_to='')),
                ('linkedin', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('website_url', models.URLField()),
                ('video_pitch', models.URLField()),
                ('team', models.CharField()),
                ('startup_details', models.TextField()),
                ('iscompleted', models.BooleanField(default=False)),
                ('under_guidance_of', models.ManyToManyField(to='users.coach_mentor_experts_others')),
            ],
        ),
    ]
