# Generated by Django 5.0.6 on 2024-05-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
