# Generated by Django 5.0.6 on 2024-05-25 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_rename_user_user_role_remove_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255)),
                ('profile_logo', models.ImageField(blank=True, null=True, upload_to='startup_logos/')),
                ('description', models.TextField()),
                ('stage', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('location_hq', models.CharField(max_length=100)),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='pitch_decks/')),
                ('linkedin', models.URLField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('video_pitch', models.FileField(blank=True, null=True, upload_to='video_pitches/')),
                ('team', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Mentor', 'Mentor'), ('Function Expert', 'Function Expert'), ('Coach', 'Coach'), ('Startup', 'Startup'), ('Partner - Company', 'Partner - Company'), ('Partner - Individual Connected', 'Partner - Individual Connected'), ('Community', 'Community'), ('Alumni', 'Alumni'), ('Guest - Tier 1', 'Guest - Tier 1'), ('Guest - Tier 2', 'Guest - Tier 2'), ('CEL Admin', 'CEL Admin'), ('DVM Admin', 'DVM Admin')], max_length=50)),
                ('profile_logo', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('sector_of_expertise', models.CharField(blank=True, max_length=100)),
                ('domain_of_expertise', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group', verbose_name='groups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='under_guidance_of',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='user_role',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user_role',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='startup',
            name='startup_champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='championed_startups_assigned', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='startup',
            name='startup_poc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poc_startups_assigned', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='startup',
            name='under_guidance_of',
            field=models.ManyToManyField(blank=True, related_name='guided_startups', to='users.userprofile'),
        ),
        migrations.DeleteModel(
            name='Coach_Mentor_Experts_others',
        ),
        migrations.DeleteModel(
            name='StartupProfile',
        ),
        migrations.DeleteModel(
            name='User_Role',
        ),
    ]
