# Generated by Django 5.0.6 on 2024-05-26 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_startup_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='data_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='registration_steps_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
