# Generated by Django 5.0.6 on 2024-05-27 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_startup_user_profile_googleuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='ggl_user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile'),
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='personal_email',
            new_name='google_email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_user_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GoogleUser',
        ),
    ]
