# Generated by Django 5.0.6 on 2024-05-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_startup_ggl_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='ggl_user_profile',
            new_name='user_profile',
        ),
    ]
