# Generated by Django 5.0.6 on 2024-06-08 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_name_alter_startup_pitch_deck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartUpMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('linkedin', models.URLField()),
                ('under_startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='users.startup')),
            ],
        ),
    ]