# Generated by Django 5.0.6 on 2024-06-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupmember',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]