# Generated by Django 5.0.6 on 2024-06-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_startup_twitter_startupmember_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='functional_areas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]