# Generated by Django 5.0.6 on 2024-06-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_startup_functional_areas_alter_startup_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
