# Generated by Django 5.0.6 on 2024-06-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_userprofile_google_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="type_of_partner",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Corporate", "Corporate"),
                    ("Investment", "Investment"),
                    ("Outreach", "Outreach"),
                    ("Ecosystem", "Ecosystem"),
                    ("Knowledge", "Knowledge"),
                    ("Community", "Community"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="google_user_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
