# Generated by Django 5.0.6 on 2024-06-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userprofile_type_of_partner_userprofile_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='domain_of_expertise',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sector_of_expertise',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]