# Generated by Django 5.0.6 on 2024-06-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_userprofile_domain_of_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Function Expert', 'Function Expert'), ('Coach', 'Coach'), ('Startup', 'Startup'), ('Partner - Company', 'Partner - Company'), ('Partner - Individual Connected', 'Partner - Individual Connected'), ('Community', 'Community'), ('Alumni', 'Alumni'), ('Guest - Tier 1', 'Guest - Tier 1'), ('Guest - Tier 2', 'Guest - Tier 2'), ('CEL Admin', 'CEL Admin'), ('DVM Admin', 'DVM Admin'), ('Angel', 'Angel')], max_length=50),
        ),
    ]