# Generated by Django 5.0.6 on 2024-06-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='offering',
            field=models.TextField(blank=True, null=True),
        ),
    ]