# Generated by Django 5.0.6 on 2024-07-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_userprofile_groups_alter_startup_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location_hq',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
