# Generated by Django 5.0.6 on 2024-07-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_startup_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_models',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='function_of_expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='horizontals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verticals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
