# Generated by Django 5.0.6 on 2024-07-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_userprofile_business_models_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Function Expert', 'Function Expert'), ('Coach', 'Coach'), ('Startup', 'Startup'), ('Partner - Company', 'Partner - Company'), ('Partner - Individual Connected', 'Partner - Individual Connected'), ('Community', 'Community'), ('Alumni', 'Alumni'), ('Guest - Tier 1', 'Guest - Tier 1'), ('Guest - Tier 2', 'Guest - Tier 2'), ('CEL Admin', 'CEL Admin'), ('DVM Admin', 'DVM Admin'), ('Angel', 'Angel'), ('Consultant', 'Consultant')], max_length=50),
        ),
    ]
