# Generated by Django 5.0.6 on 2024-07-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_userprofile_comments_userprofile_no_of_calls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='no_of_calls',
            field=models.CharField(default=' '),
        ),
    ]
