# Generated by Django 5.0.6 on 2024-07-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_userprofile_no_of_calls'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_captured', models.BooleanField(default=True)),
                ('for_consultant', models.ForeignKey(limit_choices_to={'role': 'Consultant'}, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('from_startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.startup')),
            ],
        ),
    ]
