# Generated by Django 5.0.6 on 2024-07-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_interestcapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestcapture',
            name='for_resource',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Partner - Company'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_interests', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='interestcapture',
            name='for_consultant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Consultant'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_interests', to='users.userprofile'),
        ),
    ]
