# Generated by Django 5.0.6 on 2024-07-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_userprofile_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
